---
- hosts: rpi-cluster-master
  tasks:
    - name: Create a local .kube directory
      file:
        path: ~/.kube
        state: directory
        mode: 0700

    - name: Copy .kube/config from rpi-cluster-master
      fetch:
        src: ~/.kube/config
        dest: ~/.kube/config
        flat: yes
